schemaVersion: 2.0
timeout: 60
pipelines:
  # Pipeline to build Flink from Apple branch.
  - name: publish-branch-1.14.3-apple
    branchName: branch-1.14.3-apple
    timeout: 120
    machine:
      baseImage: docker.apple.com/thomas-weise/flink-ci:latest
    trigger:
      gitPush: false
    build:
      template: freestyle:v4:publish
      steps:
        - cd /workspace
        #- ls -la ~/.m2
        #- mvn help:effective-settings -X -rf :flink-avro-confluent-registry
        - rm -rf .staged-artifacts
        - mvn clean deploy -Dscala-2.12 -Phive-3.1.3.0-apple,docs-and-source -DskipTests -Dfast -DaltDeploymentRepository=local-staging::default::file://`pwd`/.staged-artifacts
        # see https://docs.aci.apple.com/rio/guide-to-rio/package-and-publish/freeform.html
        # must exclude maven-metadata.xml
        - ci stage-lib --exclude maven-metadata.xml --exclude *.md5 --exclude *.sha1 --many-many-artifacts ./.staged-artifacts/**
        #- ci stage-lib "./target/artifacts/org/apache/flink/*/*/*.jar,org/apache/flink/"
        #- ci stage-lib "./target/artifacts/org/apache/flink/*/*/*.pom,org/apache/flink/"
    package:
      # enable for release (non -SNAPSHOT) builds
      # release: true
      freeform:
        - publish:
            - repo: m2:oss-patched

  - name: pull-request-branch-1.14.3-apple
    branchName: branch-1.14.3-apple
    timeout: 120
    machine:
      baseImage: docker.apple.com/thomas-weise/flink-ci:latest
    trigger:
      gitPush: false
    build:
      template: freestyle:v4:prb
      steps:
        - cd /workspace
        - rm -rf .staged-artifacts
        - mvn clean deploy -Pdocs-and-source -DskipTests -Drat.skip -Dscala-2.12
    package:
      # enable for release (non -SNAPSHOT) builds
      # release: true
      freeform:
        - publish:
            - repo: m2:oss-patched
